@startuml Delete Campground (DELETE)Campground

header Sample campground Sequence Diagram
footer Page %page% of %lastpage%
title "Delete Campground (DELETE)"

actor "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:campgrounds" as routerCampgrounds
participant "<<controllers>>\n:campgrounds" as controllersCampgrounds
participant "<<model>>\n:Campground" as modelCampground
database "<<MongoDB>>\n:campgrounds" as CampgroundsDatabase

client->server ++:req.delete('/campgrounds/:id')
server->routerCampgrounds ++:app.use('/api-informations/\ncampgrounds', campgrounds)
routerCampgrounds -> controllersCampgrounds ++:deleteCampground()
controllersCampgrounds->modelCampground ++:findByIdAndDelete(req.params.id)
modelCampground ->CampgroundsDatabase ++: CampgroundSchema  
CampgroundsDatabase --> modelCampground --: campground
controllersCampgrounds <-- modelCampground --:campground
controllersCampgrounds->client --:response

@enduml
