@startuml Get all Campground (GET)Campgrounds

header Sample campground Sequence Diagram
footer Page %page% of %lastpage%
title "Get all Campgrounds (GET)"

actor "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:campgrounds" as routerCampgrounds
participant "<<controllers>>\n:campgrounds" as controllersCampgrounds
participant "<<model>>\n:Campground" as modelCampground
database "<<MongoDB>>\n:campgrounds" as CampgroundsDatabase

client->server ++:req.get('/campgrounds')
server->routerCampgrounds ++:app.use('/api-informations/\ncampgrounds', campgrounds)
routerCampgrounds -> controllersCampgrounds ++:getCampgrounds()
controllersCampgrounds->modelCampground ++:find(JSON.parse(queryStr))\n.populate("reservations")
modelCampground ->CampgroundsDatabase ++: CampgroundSchema
CampgroundsDatabase --> modelCampground --: campgrounds
controllersCampgrounds <-- modelCampground --:campgrounds
controllersCampgrounds->client --:response

@enduml
